### ISSUE TITLE
Wrong image URL

### ISSUE THREAD

**Issue by YourMJK** [drewmarsh/amazon-book-cover-grabber#1]
When testing the .sh script with ASIN `B0CW23CC7L` (https://www.audible.com/pd/Not-Till-We-Are-Lost-Audiobook/B0CW23CC7L), the image URL that gets opened and downloaded is

```
https://ec2.images-amazon.com/images/P/B0CW23CC7L.01.MAIN._SCRM_.jpg
```

which points to a 1px transparent image, not the actual cover image.

**Comment by YourMJK** [comment]
Nvm, thought this was for audible audiobooks

**Comment by drewmarsh** [comment]
The best way I've found to get Audible covers is from this extension: https://github.com/book-tools/audible-cover-grabber
